/*jap offset*/
/*PokePasoParaGirathinaFormChange = 0x20772F4 | 1;
PokeList_ItemSet = 0x2080cd8 | 1;
PokeItemSetInit_Bag = 0x2080b14 | 1;
PokeItemSetYesNoMain_Bag = 0x02080e88|1;
Menu_ItemMenuItemGet = 0x02082d6c|1;
SaveData_GetEventWork = 0x020500c4 | 1;
EventWork_GetEventWorkAdrs = 0x02050198 | 1;*/
GetMonData = 0x02073CF8 | 1;
PokeStatusGet = 0x0208D4CC| 1;
PokemonAlloc = 0x020734FC| 1;
PokeReplace = 0x02076DA0| 1;
FillWindowPixelBuffer = 0x0201AA4C| 1;
ConvertNumToString = 0x0208F8FC| 1;
StringPut = 0x0208F850| 1;
PutWindows = 0x0201A64C| 1;
FreeSystem = 0x02017EE0| 1;