/*jap offset*/
/*PokePasoParaGirathinaFormChange = 0x20772F4 | 1;
PokeList_ItemSet = 0x2080cd8 | 1;
PokeItemSetInit_Bag = 0x2080b14 | 1;
PokeItemSetYesNoMain_Bag = 0x02080e88|1;
Menu_ItemMenuItemGet = 0x02082d6c|1;
SaveData_GetEventWork = 0x020500c4 | 1;
EventWork_GetEventWorkAdrs = 0x02050198 | 1;*/
GetMonData = 0x02074470 | 1;
PokeStatusGet = 0x0208DD48| 1;
PokemonAlloc = 0x02073C74| 1;
PokeReplace = 0x020774C8| 1;
FillWindowPixelBuffer = 0x0201ADA4| 1;
ConvertNumToString = 0x02090184| 1;
StringPut = 0x020900D8| 1;
PutWindows = 0x0201A9A4| 1;/*0801A64C*/
FreeSystem = 0x02018238| 1;